[package]
name = "edge-external-provisioner"
version = "0.1.0"
authors = ["Rajasekharan Vengalil <rajave@microsoft.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
